# Generated by Django 2.1.2 on 2018-11-08 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=150)),
                ('prod_description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('prod_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
