# Generated by Django 2.1.3 on 2018-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_selling',
            name='Seller',
        ),
        migrations.AddField(
            model_name='products_selling',
            name='Seller',
            field=models.ManyToManyField(to='registration.Profile'),
        ),
    ]
