# Generated by Django 2.1.3 on 2018-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackpart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='email',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
